### ISSUE TITLE
Create documentation for September release

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#1035]
## Conditions of satisfaction
- [x] Document new process for adding views to the view paragraph item
- [x] Document user management processes - draft
- [ ] Document how to take advantage of az_seo module.
- [x] Document how to create a text logo
- [x] Update AZ Person to include pronouns field
- [x] Editing media and cropping breakpoints, update "Image Crop Settings"
- [x] Space around content on Text on Media/Background
- [x] Content moderation - draft

**Comment by trackleft** [comment]
After running cron, the sitemap appears. We should add a section to https://quickstart.arizona.edu/site-organization that covers sitemaps and other related az_seo functionality since the prefix url is set to http://default/ and doesn't accept tokens.
image  https://github.com/az-digital/az_quickstart/pull/1023#issuecomment-921987585
