### ISSUE TITLE
Files should not have date in automatic path

### ISSUE THREAD

**Issue by smayden** [az-digital/az_quickstart#1110]
## Motivation
When uploading files to Quickstart 2 sites the year/month get added to the path for the file. Example:
https://quickstart.arizona.edu/sites/default/files/2021-09/Quickstart%20Whitepaper.pdf

### Is your feature request related to a problem? Please describe.
Adding the date the file path may cause a few problems:
-Makes it more difficult to replace files when updating them
-Causes URLs to change for files manually migrated

### Describe the solution you'd like
Use pathauto to just put all files /sites/default/files (matching QS1)

**Comment by joeparsons** [comment]
I don't think we want to change this default behavior in Quickstart.  This actually something that changed in Drupal core (not Quickstart) due to known performance problems that occur when file directories contain too many files.

My suggestion would be that we maintain some sort of date or field based sub-folder structure by default without preventing sites from overriding this configuration on a site by site basis as needed.

For context:
https://www.drupal.org/project/drupal/issues/2128055
https://www.drupal.org/node/3251654
https://www.drupal.org/node/2459413

**Comment by danahertzberg** [comment]
Look into updating file without changing file name needs

**Comment by joeparsons** [comment]
Per discussion in 2023-05-24 workshop, we're going to close this as resolved by the addition of the media_file_entity_replace module (#1528).
