### ISSUE TITLE
Create Person views

### ISSUE THREAD

**Issue by barrettbaffert** [az-digital/az_quickstart#117]
**Goal:** Create basic front-end views of the Person content type.

- [x]  Add and configure directory "grid" view display
- [x]  Add and configure directory "row" view display

**Comment by akslay** [comment]
Related: https://app.zenhub.com/workspaces/quickstart-20-5e8f25351c5b8596956ebb92/issues/az-digital/az_quickstart/380 See my comment concerning a patch I applied to the Draggableviews module on my branch of AZQS.

**Comment by akslay** [comment]
Running into some issues with adding a relationship (terms on node) to the view, and then using that relationship to add a term weight filter to the sort order. Using the relationship adds several duplicates, and using the "distinct" option doesn't seem to solve that problem.

I've found a few issues on Drupal that might be related to this problem:
- https://www.drupal.org/project/drupal/issues/3037255
- https://www.drupal.org/project/entity_reference_revisions/issues/2799479
- https://www.drupal.org/project/drupal/issues/2993688

Not too sure how we want to proceed, because of this issue.
