### ISSUE TITLE
Change sidebar nav to show below full-width elements

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#1202]
Changing to be below the full width elements on the page would more closely match the QS1 style. Also, blocks placed in the page bottom region are more likely to have reusable content than blocks placed in the content top region.

**Comment by danahertzberg** [comment]
I wonder if we could add a checkbox to Text on Media and Text with Background to indicate the sidebar should appear below this item. Then the navigation could look for that on large screen sizes?

**Comment by trackleft** [comment]
In order to get something like this to work, I think we will either need javascript or view modes but I don't know for certain.
<img width="1564" alt="image" src="https://user-images.githubusercontent.com/1023167/156619905-a7753560-25a1-4ba5-9ae0-e2b7708d5986.png">

We could consider using the bootstrap scrollspy, and the previously name affix but dropped from BS4 scroll position styler https://github.com/acch/scrollpos-styler in a page setting or a paragraph setting, or a block setting.

The most complex and brittle would be a flexible page setting.

If we chose to use a **block setting** we could make a form like this... though we should think about limiting which regions this would be allowed to applied in.

If a user selects one of the **sidebar regions**  for placement, this form would appear.

[x] Position block under specific element by ID or selector
-----------------------------
|   `#Paragragph-1`                |. selector this block should be below
-----------------------------
-----------------------------
|   `#Paragragph-2`                |.  selector  this block should be above
-----------------------------

Then we could add an option in the paragraph to override sidebar alignment rules
[x] do not resize column when there are sidebars on the page.

**Comment by danahertzberg** [comment]
**3/16/2022 Notes**
- QS2 functionality is seen as a bug by content editors (more with text on media)
- Workarounds include not using full width elements or using blocks
- What happens on mobile? - Current solution is first sidebar goes above page content, not ideal
- No current live sites utilize existing functionality
- What happens to display of content in full width elements?

Potential solutions
- Combo block and paragraph settings
