### ISSUE TITLE
Image quality problems

### ISSUE THREAD

**Issue by smayden** [az-digital/az_quickstart#1215]
I've noticed on a few Quickstart sites that image quality is noticeably degraded from the same images in Quickstart 1. Troy commented in the Friday meeting that CALS is seeing similar problems. 

## Problem/Motivation
Why the issue was filed, steps to reproduce the problem, etc.

### Describe the bug
Images used at similar sizing appear grainy compared to Quickstart 1
Thumbnails on youtube videos in particular are pixelated.

will add some screenshots here.

## Proposed resolution
Troy noted that QS2 uses the GD2 image toolkit and that image quality is set to 75%
/admin/config/media/image-toolkit

There may also be an impact with how some paragraphs size images based on the text (up sizing)

**Comment by trackleft** [comment]
Is this only on text on media paragraphs?
I took a fairly conservative approach when setting the image quality and size for each break point for background images in order to optimize for performance, but we can definitely up the image quality to a point where the images are unnoticeably pixelated.

If so, we might also want to change the background image style settings for each breakpoint, marketing might be able to provide some direction about what the best compromise should be considering all of the variables involved with this issue.

The outstanding question here is at what point does image weight start negatively affecting our SEO/ and site usability? 

One option could be to set the image toolkit quality setting to 100% and depend on our users to be responsible for adjusting images for performance manually via third-party tools such as https://resmush.it/

Or investigate https://www.drupal.org/project/imageapi_optimize

**Comment by smayden** [comment]
I'm definitely noticing most on Text on Media. I thought it was happening on all images, but comparing some sites, now I'm not sure.

For Text on Media, I think there are at least two different things happening:

- Thumbnials on videos load as very noticeably pixelated. See the videos at the top of these pages with how the thumbnail looks right before the vid starts to play (I need to test more the impact of swapping out the thumbnail): 
    https://covid19.arizona.edu/
    https://live-azs-arizonaedu.pantheonsite.io/
- Depending on the space around content setting, images may be upsized. This issue may no longer be a problem when we have the background aspect ratio on sites.

**Comment by smayden** [comment]
We are definitely still seeing image quality issues on Text with Media so reopening this issue (or let me know if I should create a new one).

**Comment by trackleft** [comment]
@smayden did you run the drush command? drush image:flush

**Comment by tadean** [comment]
@smayden @trackleft Beyond the image toolkit in use, one thing that's occurred to me regarding `Text on Media` is that the style in use at the top breakpoint is `az_full_width_bg_large` which is 1199 pixels. If the Text on Media is full-width, this automatically forces some upscaling takes place on desktop (since the full-width container is likely wider than the 1200 bootstrap container). 

Perhaps there should be a responsive image style intended for full width media that extends a bit beyond the 1200 container for cases like this so there is at least some extra for the most common resolutions? (1920 for example)

Granted there will always be some pixel width where it has to start upscaling eventually.

**Comment by tadean** [comment]
Also, in the case of youtube thumbnails, the youtube API is probably not delivering the high quality thumbnail initially.

**Comment by trackleft** [comment]
If we can reuse crops we could add additional responsive image styles that would not need to be configured by the content creator.

**Comment by smayden** [comment]
closing this as the linger problems were addressed in other issues.
