### ISSUE TITLE
News importer fails if less than 30 stories to import

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#1302]
### Describe the bug
When attempting to import stories with the "College of Humanities" tag, the importer successfully imported 24 files, and then quietly failed when it moved on to importing the media and left the following message in the log:
`Migration az_news_feed_stories_media did not meet the requirements. Missing migrations az_news_feed_stories_files. requirements: az_news_feed_stories_files.`

### Expected behavior

The news importer should bring in all files, media and stories successfully even if there are fewer than 30 stories.

**Comment by trackleft** [comment]
Strange were there migration messages when this occurred?

`drush mmsg az_news_feed_stories_files`
`drush mmsg az_news_feed_stories_media`

**Comment by trackleft** [comment]
Oh, i think I know what happened.

IF the tag selection changes, and there were 30 in the previously selected migration, and only 24 in the newly selected migration, the media migration fails, because it thinks there are supposed to be 30.

**Comment by smayden** [comment]
> Oh, i think I know what happened.
> 
> IF the tag selection changes, and there were 30 in the previously selected migration, and only 24 in the newly selected migration, the media migration fails, because it thinks there are supposed to be 30.

In this case, the module was enabled, then I removed "All" tag and added Humanities, then I immediately ran the import.

So I don't think it would have run already?

**Comment by trackleft** [comment]
I'm not sure, maybe the 30 was in the cache from the default.

**Comment by smayden** [comment]
No other stories were appearing on the site. Other than one starter content story

**Comment by smayden** [comment]
I can confirm that this issue is still happening on my local build:

1. Enabled the Quickstart News Feed module
2. Went to /admin/content/az-news-feeds
3. Removed the "All" tag and added a tag that I knew had less than 30 stories (e.g. Alfie Norville Gem & Mineral Museum).
4. Saved configuration
5. Went to the import page /admin/structure/migrate/manage/az_news_feeds/migrations
6. Clicked execute for UArizona News Stories
7. It looked like migration was starting to run
8. Saw a status message that it looked like only files imported and then the process stopped.

![image](https://user-images.githubusercontent.com/10873398/158485690-fdd1cf9b-24b5-47fe-8fca-50270d9c87a5.png)

I looked at /news and saw no stories, but looking at files there were temporary files related to the the new stories it was trying to import. 

I tried adding a second tag (that still wouldn't add up to 30 total stories) and the same thing happened.

I did a rollback of migration and then tested a tag that had more than 30 stories (Arts & Humanities). This was successful when I did the manual import.

Then (keeping Arts & Humanities in place), I added one of the tags back with less than 30 stories. This time it ran successfully and the stories related to that tag appeared under /news.

**Comment by danahertzberg** [comment]
Potential solutions:
- Change this to false: https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_news/az_news_feeds/config/install/migrate_queue_importer.cron_migration.az_news_feeds.yml#L2
- Remove default "All" tag
