### ISSUE TITLE
Sidebar menu covers up content on Text with Background

### ISSUE THREAD

**Issue by ejsamboy** [az-digital/az_quickstart#1331]
### Describe the bug
While working on the new Think Tank website, I noticed that the Sidebar menu (added by default to the Sidebar-first region) covers up the content on Text with Background.

### To Reproduce
1. Create a Drupal page and add Text on Media
2. Go to Structure and select Block Layout
3. Place the Sidebar menu under the Sidebar First region
4. Ensure the menu shows up on your new page

### Screenshots of the issue
![Screen Shot 2022-02-18 at 2 39 33 PM](https://user-images.githubusercontent.com/92047381/154765218-e655cd3b-557a-456d-a866-531da9d2e0c7.png)

### Expected behavior
The sidebar menu should push the content over so it doesn't cover it up.

**Comment by danahertzberg** [comment]
As of 2.1.1 release

**Comment by smayden** [comment]
From testing, I can confirm that this bug is not happening on a local 2.0.X build (so likely introduced in 2.1.1.

In comparing sites with bug and without, I notice in the inspector that the following styles appear on the az-full-width-column-content class for the version that is working:

`@media (min-width: 768px)
.layout-sidebar-first .region-content .full-width-background .az-full-width-column-content {
    -ms-flex: 0 0 75%;
    flex: 0 0 75%;
    max-width: 75%;
}`

![image](https://user-images.githubusercontent.com/10873398/156229828-0335c65e-3725-4d38-9158-e8e191bd458a.png)

**Comment by smayden** [comment]
I am wondering if the changes made to `modules/custom/az_paragraphs/css/az_paragraphs_full_width.css` in this PR are the culprit (part of 2.0.14 release on Jan 18, 2022):

https://github.com/az-digital/az_quickstart/commit/1567178d9b48671b19133b44de7d6a2a9cb83140

The text for text with background has the class "az-full-width-column-content" on it, but the associated styles seem to now be under "az-full-width-row" (line 110).
