### ISSUE TITLE
Accordion body text turns white when embedded on background color

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#1443]
## Problem/Motivation
I want to embed a flexible block with accordions in a Text with background paragraph type

### Describe the bug
Color is not set in CSS

### To Reproduce

1. Make a flexible block with accordion content
2. Embed block in Text with background paragraph type

## Proposed resolution
~~Add `color: initial;` to _card.scss file under `.card, .panel, .thumbnail, .well {}` group~~

**Updated as of 2022/06/01:**
This will become a two-part fix: a change to Bootstrap, and a change to Quickstart's Accordion.
- Quickstart: Add the `.bg-white` class to the Accordion component's `.card-body` or `collapse` section.
- Bootstrap: Remove hard-coded background-color from the `.card` class (https://github.com/az-digital/arizona-bootstrap/issues/489)

Order does not matter here; adding the `.bg-white` class to the Accordion div will allow it to leverage the built-in color contrast fallbacks.

### Expected behavior
Accordion body text should match standard body color (since it's on a white background)

### Before
![image](https://user-images.githubusercontent.com/59745109/161142483-0215e8ed-cd99-4533-b10a-efbe4f0fc164.png)

### After
![image](https://user-images.githubusercontent.com/59745109/161142631-5dbdf86b-441a-43d7-8207-d9800dfe51c7.png)

**Comment by danahertzberg** [comment]
[ ] - Test potential solution with wysiwyg editor color override.
[ ] - Look into modifying color when background is set to white.

**Comment by akslay** [comment]
The built-in color contrast in the Bootstrap SCSS is to blame for this one. It sees the `.bg-blue` (for example) and wants to turn the text white to keep it accessible, and doesn't realize that the accordion also has a white background already. 

If we were to add `.bg-white` to the accordion body (https://github.com/az-digital/az_quickstart/blob/0934444b12927f7092bae3ebc6091128054791ed/modules/custom/az_accordion/templates/az-accordion.html.twig#L33), it should basically "reset" that so it's defaulting to use black text instead of white.
