### ISSUE TITLE
Missing cache tags for entities embedded in AZ Card and AZ Accordion fields

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#1760]
## Problem/Motivation
On complex pages such as https://itsummit.arizona.edu/2022-program
Where nodes are deeply embedded via entity reference fields/views/blocks/paragraphs
Updating one of the referenced nodes doesn't update the page they are referenced on.

### To Reproduce
- Create a content block
- Create a flexible page
- Add an Accordion or Card paragraph to the page
- Embed the block in the body field of the card or accordion paragraph
- Modify the content block
- See that the changes to the embedded block on the flexible page are not reflected unless the Drupal cache is cleared

Example page: https://itsummit.arizona.edu/2022-program

## Proposed resolution
Determine how far up the stack cache tags are bubbling.
See if we can unimpede them.

### Expected behavior
Pages should contain cache tags for all entities referenced/embedded on them.

**Comment by joeparsons** [comment]
Possibly related: https://www.drupal.org/project/paragraphs/issues/2855735

**Comment by joeparsons** [comment]
Renamed issue because, at least in theory, the Pantheon Advanced Page Cache module just expires affected pages in the Pantheon Global CDN when they include cache tags referencing items that have changed.  If those cache tags are missing, that's cause of the problem is probably in Quickstart or another contrib module.

**Comment by joeparsons** [comment]
The issue turned out to be specific to our custom AZ Accordion and AZ Card field types.  The field formatters for both field types are currently using [`check_markup()`](https://api.drupal.org/api/drupal/core%21modules%21filter%21filter.module/function/check_markup/9.4.x) to render the contents of their `body` subfields.  That function does nothing to preserve the cache metadata of the rendered text/markup.

I checked the default formatter used for [text fields](https://git.drupalcode.org/project/drupal/-/blob/9.4.x/core/modules/text/src/Plugin/Field/FieldFormatter/TextDefaultFormatter.php) in Drupal core and noticed that it's using the [`processed_text` render element](https://git.drupalcode.org/project/drupal/-/blob/9.4.x/core/modules/filter/src/Element/ProcessedText.php) instead, which includes a `preRender` callback that does preserve cache metadata.

We need to update our AZ Card and AZ Accordion field formatters to do the same when rendering their body elements.
