### ISSUE TITLE
Node contextual links missing in views that render content using a display mode.

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#1963]
## Problem/Motivation
As a content editor, I would like to edit content from a view page via contextual links.

### Describe the bug
At the moment nodes rendered in views do not display contextual links on each piece of node content.

### To Reproduce

With demo content enabled
Go to /news 
Hover over individual news items
See no contextual links for editing or deleting the node.

## Proposed resolution

Add a node.twig.html that adds contextual links to the node template.

### Expected behavior

When I hover over rendered nodes, I should see a gear with links to delete or edit content.

##  Screenshots
![image](https://user-images.githubusercontent.com/1023167/193701762-4cc9c349-11cd-449d-be00-3731d6dabb82.png)

**Comment by joshuasosa** [comment]
Would you be able to clarify this issue? At the moment, using the latest version of AZQS, nodes rendered in views _do_ have node editing contextual filters in place on my testing.
![image](https://user-images.githubusercontent.com/4400438/194182539-4c625334-aeb3-4fd8-bee1-1d2969ef0fb8.png)

There is an issue though (#1519) where we're unable to actually click edit in them due to article links wrapping over the contextual filters.
