### ISSUE TITLE
Add external link indicators to menu items

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#210]
## Motivation
Website visitors can get confused if the main navigation links you out to an external page without notification.

### Is your feature request related to a problem? Please describe.
Quickstart 1.0 handles this with the arrow in the upper right corner to indicate that the link will be taking you to an external site.
<img width="343" alt="Screen Shot 2020-05-20 at 4 01 12 PM" src="https://user-images.githubusercontent.com/1509771/82506046-a538ad80-9ab3-11ea-8663-8eece4fe39a5.png">

### Describe the solution you'd like
We should match the existing functionality in QS 1.0.

### Describe alternatives you've considered
There has been some discussion about whether or not we are going to continue to use the external link indicator. 

We should make it optional, and then we would have the option of removing it in the future if it was no longer supported. Quickstart 1.0 already makes this an optional theme setting that is enabled by default (although this is site wide and not exclusive to menus):
<img width="547" alt="Screen Shot 2020-05-20 at 4 20 11 PM" src="https://user-images.githubusercontent.com/1509771/82507029-137e6f80-9ab6-11ea-99f3-a8e6505566c9.png">

### Roles and Permissions considerations
Content administrators that have access to theme settings should be able to change this setting. 
Content editors should not be able to change this setting.

**Comment by danahertzberg** [comment]
Test comment

**Comment by caosborne89** [comment]
Sounds like some conversation about this is happening. May end up being this is not needed.

**Comment by smayden** [comment]
As Chris indicated, MBM has been discussing wanting to change how we handle external links for several reasons (accessibility, UX, and analytics tracking being the main ones). We are hoping to change the default behavior to make external links open in the same tab (rather than a new tab by default in QS1). The DRC supports this change from accessibility view point.

However, the question of whether there should be an external link icon in the menu should probably be a separate question. Somethings to think about:

- Is having an external link indicator helpful for cases when external links are in the menu?
- Should other *.arizona.edu be considered external links? (I'd argue no, and would guess these are the types of links mainly being seen as external menu links now?)
- What should the external link icon (if we want that option) look like

**Comment by danahertzberg** [comment]
Thanks for the recap, @smayden! I fully support the decision from MBM to not define a target for external links and have them open in the same window.

I also agree the external link _icon_ is a separate discussion. I would defer to your UX research to determine if they are helpful and intuitive. If they are neither of these things, I would advocate for getting rid of these icons as well.

**Comment by camikazegreen** [comment]
I am personally sad about this since I prefer external links to open in a new tab, but I won't resist change.

**Comment by danahertzberg** [comment]
No longer a requirement. Not going to indicate external links.
