### ISSUE TITLE
Create new View: homepage (Trending)

### ISSUE THREAD

**Issue by mrbeiley** [az-digital/az_quickstart#2324]
## Conditions of satisfaction
- [ ] Should ‹testable condition that should be satisfied›
- [ ] Should ‹testable condition that should be satisfied›
- [ ] …

Example: https://www.screencast.com/t/pe7NgGVBhmpB

news.arizona.edu currently bases on analytics data over previous 14 days

**Comment by trackleft** [comment]
This uses the https://www.drupal.org/project/google_analytics_counter module

**Comment by HenryzGreenberg** [comment]
Marcom Sandbox - https://dev-marcomm-sandbox.pantheonsite.io/

**Comment by HenryzGreenberg** [comment]
Quick Question for the group would this module give us the same functionality without having to rely on the Google Analytics data? https://www.drupal.org/project/trending_topics

**Comment by trackleft** [comment]
On the surface, this looks like a simple request, however these are the variables involved.

Most of our sites sit behind an edge cache layer to protect our application layer from being overwhelmed by an onslaught of traffic. 

A side effect  of this is that our application layer has no knowledge about the amount of traffic each page receives

This is relevant for us, because views relies on data that the application layer has access to in order to calculate which pages are trending, or more popular than others.

With that being said, all is not lost, we do have the data somewhere, but do need to find a solution that bridges the knowledge gap between layers.

1. Google Analytics
2. HTTP Access logs
3. Pantheon data(?)
4. New Relic data (?)
