### ISSUE TITLE
Quickstart ddev config not working with latest ddev version

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az_quickstart#247]
## Problem/Motivation
Our Quickstart-packaged ddev configuration does not work when using the latest version of ddev (1.15.0).

### Describe the bug
Something seems to have changed in the way ddev works such that our ddev configuration no longer works as expected.  Specifically the custom `ddev install` command fails with the following errors:
```
fatal: destination path '/var/www/html' already exists and is not an empty directory.
                                                                 
  [RuntimeException]                                               
  File "./composer.json" cannot be found in the current directory  
                                                                   
config [-g|--global] [-e|--editor] [-a|--auth] [--unset] [-l|--list] [-f|--file FILE] [--absolute] [--] [<setting-key>] [<setting-value>]...

Composer could not find a composer.json file in /var/www/html
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Command site-install needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command.                                                    [error]
The drush command 'site:install' could not be executed.                                                                                                                                                      [error]
```
### To Reproduce

1. Install ddev version 1.15.0 locally
2. Clone az_quickstart
3. Run the following commands within the cloned working copy of the repo:
```
cp .ddev/config.quickstart.yaml .ddev/config.yaml
ddev start
ddev install
```
4. See errors

## Proposed resolution
Look into moving the `composer install`, and `yarn install` steps out of our custom ddev `install` command script and adding them as `exec` commands in the `post-start` hook in the ddev configuration file (see https://ddev.readthedocs.io/en/stable/users/extending-commands/#supported-command-hooks)

**Comment by joshuasosa** [comment]
The composer install step is not in post-start because DDEV works a bit different from Lando when it comes to restarting a project.

`lando restart` will "stop" and start an app, but not run build commands. The equivalent in DDEV would be `ddev pause` then `ddev start`. `ddev restart` will initiate `stop` and `start` commands, where containers get removed along with everything that was in them. `ddev pause` instead keeps the container, which then needs `ddev start` to start it up again. A `pause` and `start` leaves things in-tact like `lando restart` such that the container doesn't have to be rebuilt, and a developer can continue working on it without losing the container state (such as if working with the database).

Moving composer (and yarn) steps to `post-start` would then run up against this workflow by requiring the container to be rebuilt on every `start`, regardless if `stop` or `pause` was used previously.

I think the resolution for this current issue is to change the first line in `install` to `rm -r /var/www/html/*` to try to just clear out the directory.
