### ISSUE TITLE
Alternating Split Screen paragraphs don't line up in the center

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#2732]
## Problem/Motivation
It would be nice to have Split Screen elements line up cleanly in the middle of the screen when having multiple stacked elements.

### Describe the bug
When multiple split screen paragraphs are laid out consecutively with the image on alternating sides, there is a slight mis-alignment at the center of the screen.
<img width="1475" alt="Screenshot 2023-09-13 at 10 26 10 AM" src="https://github.com/az-digital/az_quickstart/assets/1509771/159def51-193a-4542-b992-cb33101b4f90">

### To Reproduce
This seems to be intermittent, but can definitely be seen clearly on our demo content:
https://demo.quickstart.arizona.edu/pages/split-screen-no-sidebar

## Proposed resolution
I think it's caused by the calculation of "half screen" not taking the scroll bar into consideration.
It may also be caused by certain image cropping options.

**Comment by bberndt-uaz** [comment]
The issue does seem to be caused by the scroll bar width only being taken into account for Split Screen paragraphs that are set to Full Width.

This styling is added to Split Screen paragraphs using the `full-width-background` class:
```
.region-content .full-width-background {
    margin-left: calc(50% - 50vw);
    margin-right: calc(50% - 50vw);
    overflow: hidden;
}
.full-width-background {
    max-width: calc(100vw - var(--scrollbar-width) / 2);
}
```

Split Screen paragraphs without the `full-width-background` class do not have values set for the `margin-left`, `margin-right`, `max-width`, `overflow-x`, and `overflow-y` properties.

I tried changing the max-width setting to simply `calc(100vw)` and that worked to align the full-width paragraphs with the non-full-width paragraphs. To resolve this issue, it would be best to do the opposite, and use the same calculation currently used for full-width paragraphs to shift over the non-full-width Split Screen paragraphs as well.
