### ISSUE TITLE
Publication Type select list filter: The filter (Drupal View exposed filter) should show only the Publication Types that are being used.

### ISSUE THREAD

**Issue by ejsamboy** [az-digital/az_quickstart#3013]
**Do not disclose security vulnerabilities here, please email us instead: 
az-digital-security@list.arizona.edu**

## Motivation
Publication Type select list filter is set to display all publication types. It should only display the Publication Types that are being used.

### Is your feature request related to a problem? Please describe.
The Publication Type select list filter has more than 30 different types, but most of the time Publications only use two or three of them. The filter should show the Publication Types in use only.

## Additional context
https://cancercenter.arizona.edu/biblio

<img width="1186" alt="Screenshot 2023-12-13 at 10 49 20 AM" src="https://github.com/az-digital/az_quickstart/assets/92047381/13b5867d-cc4f-498d-9082-31dd4fb15041">
<img width="1335" alt="Screenshot 2023-12-13 at 10 54 00 AM" src="https://github.com/az-digital/az_quickstart/assets/92047381/875e0424-6331-4bbb-abf0-9eada2461bdc">

**Comment by trackleft** [comment]
Related to #2574

**Comment by tadean** [comment]
This is what the D7 module `views_selective_filters` used to do. There is a similar D9-10 implementation in how the [calendar filter prefetches what days have events](https://github.com/az-digital/az_quickstart/blob/18aa2177e4ce60e53f1356a8e69ebaeef9f0891d/modules/custom/az_event/src/Plugin/views/filter/AZCalendarFilter.php#L65C22-L65C35) in order to highlight the calendar filter cells:

**Comment by trackleft** [comment]
Fixed by #2574
