### ISSUE TITLE
Hyperlink Land Acknowledgement text in the Global Footer

### ISSUE THREAD

**Issue by natebyerley** [az-digital/az_quickstart#3391]
## Problem/Motivation

Frank Camp in the Marketing & Communications office has requested we hyperlink the Land Acknowledgement text in the global footer. 

Can a hyperlink please be added to the 'the University of Arizona is on the land and territories of Indigenous peoples.' portion of the Land Acknowledgement, linking out to [https://storymaps.arcgis.com/stories/913da25f6c3d46658690c3800bfef48e ](https://storymaps.arcgis.com/stories/913da25f6c3d46658690c3800bfef48e )? 

Here is a screenshot of the Land Acknowledgement placement in the global footer: [https://app.screencast.com/kDck0dVEAFTOA ](https://app.screencast.com/kDck0dVEAFTOA 
)
Thank you! Catherine Gustafson 

### Update 11-18-2024:

A ServiceNow request has been received as a follow-up to this issue. See [SCTASK0058256](https://uarizona.service-now.com/nav_to.do?uri=sc_task.do%3Fsys_id=e90486cb977916108a15fae3a253af00%26sysparm_stack=sc_task_list.do%3Fsysparm_query=active=true).

> For the global footer please update the following text to be a hyperlink to https://www.arizona.edu/university-arizona-land-acknowledgment
> 
> "the University of Arizona is on the land and territories of Indigenous peoples"
> 
> Screenshot: https://app.screencast.com/Qj9wi2Sh1ppeI

## Proposed resolution

Chris Green says:

FYI, the code to change is here, [https://github.com/az-digital/az_quickstart/blob/1b175ea19531325f7585d585556d2ce751867cf7/themes/custom/az_barrio/az_barrio.theme#L133](https://github.com/az-digital/az_quickstart/blob/1b175ea19531325f7585d585556d2ce751867cf7/themes/custom/az_barrio/az_barrio.theme#L133)

I think this can be labeled good first issue

**Comment by danahertzberg** [comment]
**[joshuasosa](https://github.com/joshuasosa) commented [2 days ago](https://github.com/az-digital/az_quickstart/pull/3400#issuecomment-2097083828)**
I think it'd be better if the link went to an arizona.edu domain and if the page was set up as a set of pages. The arcgis page is fine, it works, but it's a very long page which doesn't lend itself to reading digestibility. According to the page's footer, it's put on by James E. Rogers College of Law at UArizona. Being that this statement and link appears at the bottom of every single webpage that uses AZ Quickstart, I think it's important enough and significant enough to warrant its own presence on arizona.edu instead of a third-party site.

**[danahertzberg](https://github.com/danahertzberg) commented [yesterday](https://github.com/az-digital/az_quickstart/pull/3400#issuecomment-2098732609)**
Thank you @joshuasosa! I will share the feedback with the marketing team.

**[danahertzberg](https://github.com/danahertzberg) commented [now](https://github.com/az-digital/az_quickstart/pull/3400#issuecomment-2100881375)**
> **Henry Greenberg**
> After talking with Sabre she would like to hold off doing this. Considering that this link would be on every Quickstart site she would prefer that this content live on a [Arizona.edu](http://arizona.edu/) website ( Pantheon) under CWS control. So that we can shut it down should the need arise. I will communicate this to the CWS team as well. This request started with Frank and she will be talking to him about it directly. Stay tuned…
_-[Per Slack](https://uarizona.slack.com/archives/GEKHW0CBS/p1715113333692239?thread_ts=1715102499.470389&cid=GEKHW0CBS)_

**Comment by bberndt-uaz** [comment]
I have updated the issue description: a ServiceNow request has been received with a new arizona.edu URL to use for this link, so work on this issue can proceed.
