### ISSUE TITLE
Smart Date module investigation

### ISSUE THREAD

**Issue by geijutsuka** [az-digital/az_quickstart#351]
Research the implementation of the Smart Date module: https://www.drupal.org/project/smart_date

Definition of done: it is decided whether the module will be used or not and a path forward for date handling is identified.

**Comment by danahertzberg** [comment]
Could affect recurring events handling

**Comment by tadean** [comment]
In the working session on 1/20 @camikazegreen and @tadean reached the finding that `smart_date` was a better option for our needs than `date_recur` as `date_recur` has a very basic UI for recurrence rules and generally seems less polished than `smart_date`.

We examined the following to verify that they worked:

- [ ] Timezone entry
- [ ] Recurrence rules
- [ ] Use of patch to allow Date AP Style
- [ ] Construction of a view filtering and sorting on smart date fields.

**Comment by tadean** [comment]
`smart date` was identified as the better date module option as the recurring support in `date_recur` required actual usage of actual RRULEs rather than providing an interface:

![image](https://user-images.githubusercontent.com/51835841/105376433-fbbc3580-5bc6-11eb-9bed-d5bd76f858fa.png)

Versus the more full-featured UI provided by `smart_date`:

![image](https://user-images.githubusercontent.com/51835841/105376663-36be6900-5bc7-11eb-98d5-b5ca8474c948.png)
