### ISSUE TITLE
Create Reorder People view

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#380]
**Requirements:**
- [ ] If taxonomy terms exist, allow reordering per term
- [ ] People in multiple terms should be able to have a different order in each term
- [ ] Accessible to administrators and content administrators only

**Notes:**
This issue may be relevant: https://www.drupal.org/project/draggableviews/issues/2843858

**Comment by akslay** [comment]
I've added the Draggableviews module as a dependency and applied this patch to the module on my branch of AZQS: https://www.drupal.org/files/issues/2019-12-17/draggableviews-sort_handler_specify_order_view-2767437-66.patch

There's an active issue regarding the option to choose which view your sort order should apply to not showing up. This patch fixes that. If you read through the comments, someone mentioned patch #66 no longer works on recent versions of Drupal in combination with the 2.0.0 branch of the module. I had applied this patch on a different D8 site and it works fine, and also works fine on this D9 site so I used this patch instead of the most recent one. I decided to use the #66 patch since I had already used it once without issue, and the most recent patch has only been tested by 1 person even though it's marked as R&TBTC.

**Comment by akslay** [comment]
There is an active issue for adding the link to sort/order content:
https://www.drupal.org/project/draggableviews/issues/2843858

We'll probably want to keep an eye on this so that we can hopefully have it implemented before MVP. But if not, an interim solution we could implement is to use a standard block and place it at the top of the Directory page. The block can be restricted to editor/admin roles only so that site visitors can't see or interact with the block. I did this for the D8 development site for Registrar:
![reorder_block_button](https://user-images.githubusercontent.com/52931751/99322753-dceb9c80-282d-11eb-946a-98725211d680.png)
