### ISSUE TITLE
Create Menu block block type

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#574]
Match Quickstart 1 implementation. Should be added in Content > Blocks.
- Have menu selection
- Allow selection of start level
- Allow selection of expand children
- Should be embeddable in paragraphs
- Should be organizable in Structure > Blocks

QS1 version 
![image](https://user-images.githubusercontent.com/1023167/136074476-0a2fbfad-4029-4395-91b9-ff7905b47713.png)
![image](https://user-images.githubusercontent.com/1023167/136074456-9ac77457-27f4-4951-a6cc-77761068625f.png)

**Comment by danahertzberg** [comment]
Hey @jwmoore1 I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/quickstart-20-5e8f25351c5b8596956ebb92/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_

**Comment by bberndt-uaz** [comment]
@danahertzberg  Dana, would you be able to provide an example or two of these menus?

@jwmoore1, @cpoff, and I looked at the [Menu Block module](https://www.drupal.org/project/menu_block) which is installed and enabled with Quickstart. From the instructions in the [README](https://git.drupalcode.org/project/menu_block/tree/8.x-1.7), it seems that these blocks can only be added and configured by an admin user in /admin/structure/block.

In order to allow content editors to embed and edit the menu blocks within paragraphs, we may need to create a custom module similar to the [Select Menu](https://github.com/az-digital/az_quickstart/issues/576) that @trackleft worked on. I'm not sure how much work this would take or if this issue should be pushed to 2.3.0.

**Comment by trackleft** [comment]
I wonder if we can add menu block and select menu block to the /block/add page?

**Comment by danahertzberg** [comment]
Here are some examples of this block in QS1
- https://eller.arizona.edu/programs/mba/full-time/admissions
- https://law.arizona.edu/jd

After discussion today, a good solution would be to add a new button to the CKEditor that embeds only blocks of this new menu block type. (like "Embed menu block" button)

**Comment by joeparsons** [comment]
The CKEditor embed buttons are provided by the [Entity Embed module](https://www.drupal.org/project/entity_embed) and are for embedding _content_ entities inside text areas fields.  The blocks created via the [Menu Block module](https://www.drupal.org/project/menu_block) are _configuration_ entities.

In Quickstart 1 we used the [Menu Bean module](https://www.drupal.org/project/menu_bean) which provided a way to create block (content) types that worked a lot like Menu Blocks but could also have additional content fields added to them.  I don't know of any module that provides the same functionality in Drupal 9.

There are a couple of different ways I can think of that we could create our own (content) menu block type:
- Add the [Field Menu module](https://www.drupal.org/project/field_menu) which provides a menu field type that can be added to any content entity bundle (e.g. block type).  The way menus are configured/rendered looks similar to how the Menu Block module works.
- Implement our own "menu" field plugin(s) (field type, field widget, field formatter)

**Comment by joeparsons** [comment]
One other method we could consider would be to create a new MenuBlockEntity class that extends [`Drupal\block_content\Entity\BlockContent`](https://git.drupalcode.org/project/drupal/-/blob/9.3.x/core/modules/block_content/src/Entity/BlockContent.php) to add menu fields/functionality.  This would actually be most similar to the way that the Menu Bean module's implementation worked in D7.

**Comment by trackleft** [comment]
The path I am planning to take is to add the [field_menu module](https://www.drupal.org/project/field_menu), and export config for the `block_content` entity with a bundle name of `az_menu`.  Adding a new module for this is a bit disappointing, since we already have menu blocks and a plugin that extends menu blocks, but as far as I can tell, the only way to make the user experience work as expected, is to use block_content entities.

This would fill the requirements of being able to add a block via the `/block/add ` page,  and allow embedding via the ckeditor's embed content block button.

I did start down the road of creating a new `MenuBlockEntity` class that extends [Drupal\block_content\Entity\BlockContent](https://git.drupalcode.org/project/drupal/-/blob/9.3.x/core/modules/block_content/src/Entity/BlockContent.php), but I beileve that creates a new entity type, which means that we would need to create yet another ckeditor button, since those are limited by entity type.

Also investigated adding a `Derivative` Plugin, and a block plugin, but neither of those seem to fit our needs.

Also investigated adding a new ckeditor button for adding the existing configuration entity menu blocks, but found errors with that method.

Also investigated using hook_form_id_alter, but I think that would just add a lot of duplicate code from menu_block.

**Comment by joeparsons** [comment]
@tadean identified another contrib module that might facilitate this functionality (alternative to field_menu):
https://www.drupal.org/project/block_field

**Comment by trackleft** [comment]
I've been quietly working on this issue for a while now, and have stumbled across some very interesting threads on drupal.org concerning our ideas about embedding blocks in content.

Specifically this issue https://www.drupal.org/project/drupal/issues/2704331

In the linked issue, some fairly respected contributors are saying things like... Blocks should not be embedded in content.

For us, a key selling point of Quickstart is the ability to embed blocks in content, or rather easily build complex pages with simple building blocks, but that seems at odds with what "blocks are for".

**Comment by joeparsons** [comment]
> I think we should all come to a consensus about the path we want to pursue regarding embedding blocks.

I'd like to explore the feasibility of the way of Berdir suggested adding blocks within Paragraphs in that issue thread as an alternative to embedding them:

https://www.drupal.org/project/drupal/issues/2704331#comment-14604615
>block_content entities are exposed as block plugins and saving reusable blocks triggers a block plugin discovery. The more of them you have the more expensive that becomes.
>
>Layout Builder places block_content entities as blocks and ***paragraphs can do that do through [block_field](https://www.drupal.org/project/block_field)***.

**Comment by trackleft** [comment]
Created new tickets to address some of the concerns mentioned here.
https://github.com/az-digital/az_quickstart/issues/1854
https://github.com/az-digital/az_quickstart/issues/1852
https://github.com/az-digital/az_quickstart/issues/1851
https://github.com/az-digital/az_quickstart/issues/1850
