### ISSUE TITLE
Add Workbench moderation

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#577]
Match Quickstart 1 features and permissions.

https://www.drupal.org/project/workbench

---------------------------------

**Update as of 3/24/2021:**
Instead of matching UAQS 1.0 we will modify the transitions to the following:

- Draft
- Set to published
- Set to unpublished

Modify permissions as follows:
- Allow editors to publish/approve content

**Comment by akslay** [comment]
I made a fresh build of UAQS, and it looks like the module UAQS D7 is using is actually [Workbench Moderation](https://www.drupal.org/project/workbench_moderation) rather than Workbench. Workbench Moderation has been replaced by **Content Moderation** in Drupal core for D8/9. I'll move forward using Content Moderation instead.
