### ISSUE TITLE
Files list shows incorrect number of “used in” instances (patch)

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/az_quickstart#585]
_SASG found original bug._

Files list shows incorrect number of “used in” instances--always defaulting to “1 place” even when it’s not actually in use.

This is actually a bug in the Files view. There’s no patch available that I found, but there is a simple fix. Click on the “used in” field in the View, and change “1 place” to “@count place”.

https://www.drupal.org/project/drupal/issues/2887988

Related core issue regarding file deletion of unused files: https://www.drupal.org/project/drupal/issues/2821423

**Comment by akslay** [comment]
@joeparsons @tadean 

https://www.drupal.org/project/drupal/issues/2887988#comment-13522987
Do either of you know where the best place to put this change would be? It's a change to Drupal's "Files" view, so I assume it needs to be placed in a `quickstart` directory somewhere since it's an override. But I'm not positive where in the AZQS repo that should be. Just root `config > install` ? Or `az_core` ?

**Comment by akslay** [comment]
Closing this issue in favor of waiting for overall core fix.
