### ISSUE TITLE
Default PHPUnit configuration doesn't work for lando/ddev

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az_quickstart#66]
## Problem/Motivation
The default path provided for the `bootstrap` option in our `phpunit.xml.dist` configuration file works for ProboCI but does not work for lando or ddev.

### Describe the bug
In our `phpunit.xml.dist` configuration file we current specify these top level attributes:
```<phpunit bootstrap="../../../core/tests/bootstrap.php" colors="true">```
The path provided for the bootstrap script was based on what worked for ProboCI.  Unfortunately, in order for someone to run our PHPUnit tests with lando or ddev, they need to modify that value to be `/app/web/core/tests/bootstrap.php`.

### To Reproduce
Try running phpunit inside a lando or ddev container.

## Proposed resolution
We should either make the `bootstrap` value provided in `phpunit.xml.dist` be something that works on more environments or consider removing it and document how to specify a bootstrap value at runtime using the `--bootstrap` command line option.

### Expected behavior
Someone following our documented steps for running PHPUnit tests should not need to make changes to the `phpunit.xml.dist` file.  Our ProboCI configuration could be changed to provide runtime configuration options as needed.

**Comment by trackleft** [comment]
In the meantime here is how I was able to get it to work: 

root@3dde9712f1f8:/app/web/profiles/custom/az_quickstart# /app/vendor/bin/phpunit -v -c phpunit.xml.dist --bootstrap=/app/web/core/tests/bootstrap.php

**Comment by trackleft** [comment]
FYI, my fix above doesn't work in the profile, just on core and contrib modules.  Still having issues with the symlink.

**Comment by trackleft** [comment]
What do you think of this as a solution? https://stackoverflow.com/a/19155381/1086610

**Comment by tadean** [comment]
Interesting idea - something similar seems like it might potentially work in our case.

**Comment by trackleft** [comment]
Upon extensive investigation, I found the following steps will enable running functional tests within lando.

Step 1. In the .lando.yml file do add az-quickstart-install as a named volume
```
diff --git a/.lando.yml b/.lando.yml
index 074cff1..891c0d2 100644
--- a/.lando.yml
+++ b/.lando.yml
@@ -15,7 +15,7 @@ services:
         # Don't share our host working directory as /app. We want /app empty for composer.
         - /app
         # Instead share our host working directory as a standalone package.
-        - .:/usr/local/quickstart-install-profile
+        - quickstart:/usr/local/quickstart-install-profile
     build:
       # Create a new quickstart project and use the installation profile as a non-packagist repository.
       # Use the matching scaffolding branch if available.
@@ -55,3 +55,6 @@ tooling:
       # Now issue a composer update/install for the scaffolding folder to pull in new dependencies.
       # "true" command consumes passed Lando arguments that were only intended to be passed to the previous call.
       - composer --working-dir=/app --no-scripts update && composer --working-dir=/app install && true
+volumes:
+  quickstart:

```
2. `export BROWSERTEST_OUTPUT_DIRECTORY="/app/web/sites"`
3. Follow the crazy step in this comment on d.o. https://www.drupal.org/project/drupal/issues/2867042#comment-13310641
4. Suddenly everything works, you can even just use `phpunit` instead of `/app/vendor/phpunit`


Not sure if this whole thing breaks Troy's previous work in regards to symlinking the profile though.

**Comment by trackleft** [comment]
This might break the way we checkout quickstart profile branches with lando FYI

**Comment by tadean** [comment]
I tested out the above - `quickstart:/usr/local/quickstart-install-profile` has the effect that the source code is no longer being shared from the host. Composer is falling back on a packagist copy of `az_quickstart` rather than your local copy and the lack of symlink seems to be why phpunit starts working:

```
www-data@66907464f915:/app/web/profiles/custom$ ls -l /usr/local/quickstart-install-profile/
total 0
www-data@66907464f915:/app/web/profiles/custom$ ls -l /app/web/profiles/custom/
total 4
drwxr-xr-x 8 www-data www-data 4096 Apr 10 15:44 az_quickstart
```
`Installing az-digital/az_quickstart (dev-master 3958aa4): Cloning 3958aa4756 from cache`

I think the cause of the original issue is that when phpunit starts up, it seems to think that it's running in `/usr/local/quickstart-install-profile/` rather than `/app/web/profiles/custom/az_quickstart`, the symlink path. So when it tries to process `bootstrap="../../../core/tests/bootstrap.php"` in `phpunit.xml.dist` it can't find its way back to the Drupal codebase. Maybe there's an alternate way to invoke it so that it understands what path it's actually supposed to be in...

**Comment by trackleft** [comment]
Once this is all sorted out we might consider a git pre-push hook within lando
https://www.git-scm.com/docs/githooks#_pre_push

**Comment by camikazegreen** [comment]
PR #164 resolved this issue.
