### ISSUE TITLE
Accordion styles should match bootstrap

### ISSUE THREAD

**Issue by smayden** [az-digital/az_quickstart#739]
Accordion styles should match Arizona Bootstrap.
https://digital.arizona.edu/arizona-bootstrap/docs/2.0/components/collapse/#accordion-example

**Comment by smayden** [comment]
Curious to know if this issue has already been addressed or what requirements are still outstanding. Any thoughts @camikazegreen?

This is how they are currently looking:

![image.png](https://images.zenhubusercontent.com/5f48298be6cde55c5263eaa0/2308a3c9-ffd8-46a8-a5e3-92d3a2f61bbc)

**Comment by akslay** [comment]
@smayden Looks like this is still a problem in the most recent release of Quickstart; I've been noticing it on all of our 2.0 sites. From what I can see, the `h3` tag inside the Accordion header is to blame, since headings have margin. Just need to update the classes on the heading tag so it's using these classes instead: `h-6 my-0` (removes classes `h5 bold mt-0`).

**Comment by akslay** [comment]
Correction to me above statement: I just realized there's an `h3` nested inside another `h3`. Just need to change the `h3` inside the `button` to a `span`.

**Comment by akslay** [comment]
https://github.com/az-digital/az_quickstart/pull/1335
