### ISSUE TITLE
Investigate merge of Config Distro not incorporating theme settings.

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#933]
**Do not disclose security vulnerabilities here, please email us instead: 
az-digital-security@list.arizona.edu**

## What is the problem that we want to solve?
When we merged #856 to fix theme related issues, the changes were not captured by Config Distro and had to be manually applied to sites after installing the updates. 

We need to understand why.

The ones that seem to have the most issue were net-new settings that we would have expected to be applied.

## Conditions of satisfaction
- [ ] The considered options are documented
- [ ] A recommended next step is documented
- [ ] An estimate of time and effort is provided for the recommendation
- [ ] …

**Comment by tadean** [comment]
It was discovered that this was due to early adopter sites having saved the theme settings form and this committing auto-generated `bootstrap_barrio` default form settings to the theme settings for some settings where we were not yet providing defaults (on region classes). This lead to behavior where when we did provide defaults for those settings, some early adopter sites had `config_distro` customizations for those theme settings.

It's suggested that whenever we make changes that cause additional theme settings to be created, we also provide a default value for that theme setting in the same pull request to avoid this issue in the future.
